fieldLayouts:
  0cf11189-ce82-45a0-928e-38af3cb14886:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 58654a1a-4c01-434f-adf9-c0c1663c7b80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d26ee64-a749-4528-b206-f147f95fd95e # Navigation - LInk
            instructions: null
            label: Link
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4652b83-284e-4c0b-938f-bd79435dc77e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f55d198-22c5-4a5b-a6b6-bca304025852
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 585e4f7d-8f46-4f8c-b63b-80b4fc80b08b # Navigation
sortOrder: 1
titleFormat: '{navigationLink.getText()}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
