fieldLayouts:
  dc507b33-5479-436f-b484-4ad0811d8b73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 16aa8946-f2d1-4850-a767-d3063da7e0b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3cc550c-fc28-4ee9-9be6-7ef998d866a9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49685c62-edc3-43fc-972b-c7231b2cdd3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: a9717584-91b9-411f-b32f-2cef03af691e
            userCondition: null
          -
            elementCondition: null
            fieldUid: 95152ca3-0b9f-4d46-9349-cd429a4e43ea
            instructions: null
            label: Builder
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7e419f6-4297-4c15-89c8-a8bb901056a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7dc373f-041f-4799-bbde-e8f7af3f1ec0
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 24af7e7f-3b66-4f65-b596-3c1c1bc4161f # Home
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
