columnSuffix: null
contentColumnType: string
fieldGroup: 84aef975-f98d-44f6-8450-a081ab798069 # Common
handle: blogRelatedCat
instructions: null
name: Category
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:d71a42f3-d21a-46fc-9d2d-3d62f1fb78da' # Blog
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
