columnSuffix: vvhxitdd
contentColumnType: text
fieldGroup: 84aef975-f98d-44f6-8450-a081ab798069 # Common
handle: body
instructions: null
name: Body
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
